import React from "react";
import {
  Container,
  Title,
  Paragraph,
  UnorderedList,
  ListItem,
  DisclaimerHeader,
} from "./DisclaimerPolicy.style";
import Header from "../../Main/Pages/NavBar/navbar";
import Footer from "../../Main/Pages/Footer/Footer";

const DisclaimerPolicy = () => {
  return (
    <>
      <Header />
        <DisclaimerHeader>
          <Title>Disclaimer Policy</Title>
          <Paragraph style={{ textAlign: "center" }}>
            We try to keep the Website (hereinafter referred to as “Platform”)
            up and running and free of annoyances. But we make no promises that
            we will succeed.
          </Paragraph>
        </DisclaimerHeader>
      <Container>

        <Paragraph style={{ fontSize: "30px", fontWeight: "bold" }}>
          Here's a refined version of your point for use in a professional
          disclaimer:
        </Paragraph>
        <Paragraph>
          THE COMPANY IS PROVIDED “AS IS” AND “AS AVAILABLE” BASIS AND TO THE
          EXTENT PERMITTED BY LAW WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS
          OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES FOR A
          PARTICULAR PURPOSE, TITLE, AND NON- INFRINGEMENT. IN ADDITION, WHILE
          THE COMPANY ATTEMPTS TO PROVIDE A GOOD USER EXPERIENCE, WE DO NOT
          REPRESENT OR WARRANT THAT: (A) THE PLATFORM WILL ALWAYS BE SECURE, AND
          ERROR-FREE, (B) THE PLATFORM WILL ALWAYS FUNCTION WITHOUT DELAYS,
          DISRUPTIONS, OR IMPERFECTIONS; OR (C) THAT ANY CONTENT, USER CONTENT,
          OR INFORMATION YOU OBTAIN ON OR THROUGH THE PLATFORM WILL BE TIMELY OR
          ACCURATE.
        </Paragraph>

        <Paragraph>
          THE PLATFORM DOES NOT PROVIDE ANY FORM OF PROFESSIONAL ADVICE,
          INCLUDING LEGAL, FINANCIAL, MEDICAL, OR TECHNICAL ADVICE. THE CONTENT
          IS USER-GENERATED, AND WE DO NOT REVIEW, VERIFY, OR ENDORSE ANY ADVICE
          POSTED BY USERS.USERS ARE ADVISED TO CONSULT WITH APPROPRIATE
          PROFESSIONALS FOR ADVICE BEFORE TAKING ANY ACTIONS BASED ON CONTENT
          FROM THE PLATFORM.
        </Paragraph>

        <Paragraph>
          YOU UNDERSTAND AND AGREE THAT YOU MAY BE EXPOSED TO CONTENT THAT MIGHT
          BE OFFENSIVE, ILLEGAL, MISLEADING, OR OTHERWISE INAPPROPRIATE, NONE OF
          WHICH THE COMPANY WILL BE RESPONSIBLE FOR.
        </Paragraph>

        <Paragraph>
          THE PLATFORM MUST NOT BE USED FOR ANY UNLAWFUL OR PROHIBITED
          ACTIVITIES. USERS ENGAGING IN FRAUDULENT, ABUSIVE, OR ILLEGAL
          ACTIVITIES WILL HAVE THEIR ACCOUNTS SUSPENDED. THE PLATFORM IS NOT
          INTENDED FOR USE BY INDIVIDUALS UNDER THE AGE OF 13. ANY ACCOUNTS
          FOUND TO BELONG TO USERS UNDER THIS AGE WILL BE SUSPENDED. CONECTYU IS
          A PLATFORM FOR PROFESSIONAL NETWORKING AND COLLABORATION. ANY MISUSE
          OF THE PLATFORM WILL BE SUBJECT TO ACTION UNDER APPLICABLE LAWS.
        </Paragraph>

        <Paragraph>
          THE COMPANY WILL NOT BE RESPONSIBLE FOR ANY DAMAGE SUFFERED BY USERS
          FROM THE USE OF THE PLATFORM PROVIDED ON THE SERVICES AVAILABLE ON THE
          PLATFORM OR THE CONTENT ON THIS PLATFORM. THIS INCLUDES BUT IS NOT
          LIMITED TO LOSS OF REVENUE/DATA RESULTING FROM DELAYS, AS MAY OCCUR
          BECAUSE OF ANY ACT/OMISSION OF PARTIES. THIS DISCLAIMER OF LIABILITY
          ALSO APPLIES TO ANY DAMAGES OR INJURY CAUSED BY ANY FAILURE OF
          PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECTS, DELAYS
          IN OPERATION OR TRANSMISSION, COMPUTER VIRUSES, COMMUNICATION LINE
          FAILURE, THEFT OR DESTRUCTION OR UNAUTHORIZED ACCESS TO, ALTERATION
          OF, OR USE OF RECORDS, WHETHER FOR BREACH OF CONTRACT, TORTUOUS
          BEHAVIOUR, NEGLIGENCE, OR UNDER ANY OTHER CAUSE OF ACTION.
        </Paragraph>

        <Paragraph>
          THE PLATFORM MAY INCLUDE LINKS TO EXTERNAL WEBSITES THAT ARE NOT
          AFFILIATED WITH CONECTYU HIVE PRIVATE LIMITED. WE DO NOT GUARANTEE THE
          ACCURACY, RELEVANCE, OR COMPLETENESS OF ANY INFORMATION ON THESE
          EXTERNAL SITES. WE ARE NOT RESPONSIBLE FOR ANY INFORMATION OR SERVICES
          PROVIDED BY THIRD-PARTY WEBSITES LINKED THROUGH THE PLATFORM.
        </Paragraph>

        <Paragraph>
          THE COMPANY ALSO MAKES IT CLEAR THAT IT SHALL NOT BE HELD LIABLE FOR
          ANY DAMAGE/HURT/INCONVENIENCE CAUSED TO THE USER THROUGH THE COURSE OF
          USAGE OF THE PLATFORM AND/OR CONTENT OR AS A RESULT OF THE USERS’
          ACTIONS. THE COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE
          CONDUCT OF THE USERS. THE CONTENT ON THE PLATFORM ARE INTENDED TO BE
          SUBJECT TO AVAILABILITY, WITHOUT ANY PROMISES OR GUARANTEES ON THE
          SAME BY THE COMPANY OR BY THE PLATFORM, AND WHILE CERTAIN INFORMATION
          AVAILABLE ON THE PLATFORM IS THE PROPERTY OF THE COMPANY AND THE
          COMPANY ENDEAVOURS TO KEEP THE SAID INFORMATION UPDATED AND ACCURATE,
          THE COMPANY SHALL NOT MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY
          KIND, EXPRESS OR IMPLIED, ABOUT THE COMPLETENESS, ACCURACY,
          RELIABILITY, SUITABILITY OR AVAILABILITY WITH RESPECT TO THE PLATFORM
          OR THE INFORMATION, OR RELATED GRAPHICS CONTAINED ON THE PLATFORM FOR
          ANY PURPOSE. ANY RELIANCE YOU PLACE ON SUCH INFORMATION IS THEREFORE
          STRICTLY AT YOUR OWN RISK.
        </Paragraph>

        <Paragraph>
          THE COMPANY BEARS NO RESPONSIBILITY WHATSOEVER FOR ANY CONSEQUENCES
          ARISING FROM THE USE OF THE PLATFORM BY USERS. THE USE OF THE PLATFORM
          IS THE SOLE RESPONSIBILITY OF THE USER (OR LEGALLY AUTHORISED PERSON
          ON BEHALF OF THE USER), AND IN CASE OF ANY NEGLIGENCE ON THE PART OF
          THE USER IN ACTING ON THE SAME SHALL NOT BE CONSTRUED AS IMPOSING ANY
          LIABILITY, DIRECT OR INDIRECT, ON THE COMPANY/ PLATFORM.
        </Paragraph>

        <Paragraph>
          THE COMPANY SHALL DISCLAIM ALL RESPONSIBILITY AND OWNS NO LIABILITY TO
          USERS FOR ANY OUTCOME (INCIDENTAL, DIRECT, INDIRECT OR OTHERWISE) FROM
          THE USE OF THE PLATFORM. IN NO EVENT WILL THE COMPANY BE LIABLE FOR
          ANY LOSS OR DAMAGE, INCLUDING WITHOUT LIMITATION, INDIRECT OR
          CONSEQUENTIAL LOSS OR DAMAGE, OR ANY LOSS OR DAMAGE WHATSOEVER ARISING
          FROM LOSS OF DATA OR PROFITS ARISING OUT OF, OR IN CONNECTION WITH,
          THE USE OF THE PLATFORM .
        </Paragraph>

        <Paragraph>
          THROUGH THIS PLATFORM, YOU ARE ABLE TO LINK TO OTHER PLATFORM WHICH
          ARE NOT UNDER THE CONTROL OF THE COMPANY. WE HAVE NO CONTROL OVER THE
          NATURE, CONTENT, AND AVAILABILITY OF THOSE SITES. THE INCLUSION OF ANY
          LINKS DOES NOT NECESSARILY IMPLY A RECOMMENDATION OR ENDORSE THE VIEWS
          EXPRESSED WITHIN THEM. EVERY EFFORT IS MADE TO KEEP THE PLATFORM UP
          AND RUNNING SMOOTHLY. HOWEVER, THE COMPANY TAKES NO RESPONSIBILITY
          FOR, AND WILL NOT BE LIABLE FOR, THE PLATFORM BEING TEMPORARILY
          UNAVAILABLE DUE TO TECHNICAL ISSUES BEYOND OUR CONTROL.
        </Paragraph>

        <Paragraph>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY WILL
          HAVE NO LIABILITY RELATED TO USER CONTENT ARISING UNDER INTELLECTUAL
          PROPERTY RIGHTS, LIBEL, PRIVACY, PUBLICITY, OBSCENITY OR OTHER LAWS.
          THE PLATFORM ALSO DISCLAIMS ALL LIABILITY WITH RESPECT TO THE MISUSE,
          LOSS, MODIFICATION, OR UNAVAILABILITY OF ANY USER CONTENT.
        </Paragraph>

        <Paragraph>
          THE USER UNDERSTANDS AND AGREES THAT ANY MATERIAL OR DATA DOWNLOADED
          OR OTHERWISE OBTAINED THROUGH THE PLATFORM ARE DONE ENTIRELY AT
          HIS/HER OWN DISCRETION AND RISK, AND HE/SHE WILL BE SOLELY RESPONSIBLE
          FOR ANY DAMAGE TO HIS/HER COMPUTER SYSTEMS OR LOSS OF DATA THAT
          RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR DATA.
        </Paragraph>

        <Paragraph>
          THE PLATFORM MAY CONNECT TO THIRD-PARTY PAYMENT GATEWAYS FOR
          PROCESSING PAYMENTS. USERS MUST ENSURE THAT PAYMENT INFORMATION IS
          ACCURATE AND UP TO DATE. THE PLATFORM CURRENTLY SUPPORTS ONE-TIME
          PURCHASES, WITH PLANS TO INTRODUCE RECURRING SUBSCRIPTIONS SOON. THE
          SUBSCRIPTION RENEWAL PERIOD WILL DEPEND ON THE PLAN CHOSEN BY THE
          USER. THE PLATFORM IS AVAILABLE FOR USERS WORLDWIDE.
        </Paragraph>

        <Paragraph>
          USERS MAY CANCEL THEIR SUBSCRIPTIONS AT ANY TIME WITHOUT A NOTICE
          PERIOD. NO REFUNDS WILL BE ISSUED EXCEPT IN CASES WHERE A PAYMENT HAS
          BEEN MADE MORE THAN ONCE FOR THE SAME SERVICE. REFUNDS OR ADJUSTMENTS
          WILL BE MADE BASED ON USER PREFERENCE. THERE ARE NO EXCLUSIONS FOR
          REFUNDS BEYOND THE CASE OF DUPLICATE PAYMENTS.
        </Paragraph>

        <Paragraph>
          WE WILL COMMUNICATE WITH USERS VIA EMAIL, AND USERS CAN REACH US
          THROUGH EMAILS OR REPORT ISSUES THROUGH THE PLATFORM'S FORUMS.
        </Paragraph>

        <Paragraph style={{ fontWeight: "bold" }}>
          DATA RETENTION POLICY:{" "}
        </Paragraph>
        <UnorderedList>
          <ListItem>
            FOR ACTIVE USERS, DATA WILL BE RETAINED INDEFINITELY.
          </ListItem>
          <ListItem>
            FOR DELETED ACCOUNTS, DATA WILL BE RETAINED FOR 30 DAYS.
          </ListItem>
        </UnorderedList>

        <Paragraph>
          WE MAY UPDATE THIS DISCLAIMER POLICY PERIODICALLY WITHOUT NOTICE.
          USERS ARE ENCOURAGED TO REVIEW THIS POLICY FOR UPDATES REGULARLY.
        </Paragraph>
      </Container>

      <Footer />
    </>
  );
};

export default DisclaimerPolicy;