// src/TermsConditionSettings/TermsConditionSettings.jsx

import React from "react";
import {
  Container,
  TermContainer,
  Subtitle,
  Para,
} from "./TermsConditionSettings.style";
import {
  Subheading,
} from "../../../../../style/PrimaryStyles/PrimaryStyles";

const TermsConditionSettings = () => {
  return (
    <Container>
      {/* <Title>Terms & Condition</Title> */}
            <Subheading>Terms & Condition</Subheading>
      
      <TermContainer>
        {/* <Header1>TERMS OF USE OF THE TOPPER ACADEMY</Header1> */}

        <Subtitle>
          Welcome to The Topper Academy’s Terms of Use for Website and
          Application
        </Subtitle>
        <Para>
          This Website and Application is created and operated by Roy Career
          Solutions Private Limited, parent company of the “The Topper Academy”.
          This legal agreement is an electronic record in terms of Indian
          Information Technology Act, 2000 and rules there under as applicable
          and the amended provisions about electronic records in various
          statutes as amended by the Indian Information Technology Act, 2000.
          This electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </Para>
        <br />
        <Para>
          This legal document is published in accordance with the provisions of
          Rule 3 (1) of the Indian Information Technology (Intermediaries
          guidelines) Rules, 2011 and Rule 4 of the Information Technology
          (Reasonable security practices and procedures and sensitive personal
          data or information) Rules, 2011 of Information Technology Act, 2000
          amended through Information Technology Amendment Act, 2008 that
          require publishing the Terms of Use and practices for access or usage
          of “info@thetopperacademy.com”
        </Para>

        <Para>
          Understanding that every individual’s path is unique, we offer
          personalized care crafted with the highest level of expertise. While
          outcomes may vary, we encourage you to explore what aligns best with
          your needs. Our team is here to support you at every stage of your
          journey.
        </Para>

        <Para>
          We respect you and take the information provided by you very seriously
          and hence the creator of this Terms of Service ensures a steady
          commitment with regard to the protection of your invaluable
          information also to support the ongoing cause that you may share
          across on this Platform. We ask for this information so that we can
          understand more about the people who support us. The creator of these
          Terms of Use ensures your steady commitment to the usage of the
          Website and Application and the services provided by the “The Topper
          Academy” on the Website and Application “The Topper Academy”.
        </Para>

        <Para>
          For the purpose of these Terms of Use (“Terms of Use”), wherever the
          context so requires, “We”, “Our”, and “Us” shall mean and refer to the
          Website and Application and/or the “The Topper Academy”, as the
          context so requires. “You”, “Your”, “Yourself”, “User” shall mean and
          refer to natural and legal individuals who shall be Users of this
          Website and Application provided by the “The Topper Academy” and who
          is competent to enter into binding contracts, as per Indian laws.
          “Third Parties” refer to any Website and Application, Platform or
          individual apart from the Users and the creator of this Website and
          Application. “Website and Application” refers to the Website and
          Application created by the “The Topper Academy”.
        </Para>

        <Subtitle>GENERAL TERMS</Subtitle>
        <Para>
          i.The headings of each section in these Terms of Use or Privacy Policy
          are only for the purpose of organizing the various provisions under
          these Terms of Use and the Privacy Policy in an orderly manner and
          shall be used by either Party to interpret the provisions contained
          herein in a manner as may apply to the Users. Further, it is
          specifically agreed to by the Parties that the headings shall have
          legal or contractual value on You using the Website and Application.
          ii.The use of this Website and Application by You is solely governed
          by these Terms of Use, Privacy Policy that may be uploaded on the
          Website and Application and any modifications or amendments made
          thereto by Us from time to time, at our sole discretion. If You as a
          User continue to access and use this Website and Application, You are
          agreeing to comply with and be bound by the following Terms of Use and
          Privacy Policy. iii.You expressly agrees and acknowledges that these
          Terms of Use and Privacy Policy are coterminus in nature and that
          expiry/termination of either one will lead to the termination of the
          other. iv.You unequivocally agree that these Terms of Use and the
          Privacy Policy constitute a legally binding agreement between You and
          Us, and that You shall be subject to the rules, guidelines, policies,
          terms, and conditions applicable to your use of the Website and
          Application, and that the same shall be deemed to be incorporated into
          these Terms of Use and shall be treated as part and parcel of the
          same. You acknowledge and agree that no signature or express act is
          required to make these Terms of Use and the Privacy Policy binding on
          You and that your act of visiting any part of the Website and
          Application constitutes the User’s full and final acceptance of these
          Terms of Use and the Privacy Policy. v.We reserve the sole and
          exclusive right to amend or modify these Terms of Use without any
          prior permission or intimation to You, and You expressly agrees that
          any such amendments or modifications shall come into effect
          immediately. If You do not adhere to the changes, You must stop using
          the Website and Application at once. Your continued use of the Website
          and Application will signify your acceptance of the changed terms.
        </Para>

        <Subtitle>REGISTRATION</Subtitle>

        <Para>
          You are required to register yourself on the Website and Application
          in order to avail the Website and Application and its services. For
          the purpose of registration, you shall be required to provide the
          Email Id on the registration link available on the homepage of the
          Website and Application. The Registrations shall be deemed complete
          only upon your's authentication and verification of your's details
          through email authentication. As a responsible Website and
          Application, we do not let you link your social media with the Website
          and Application for registration purpose or otherwise.
        </Para>

        <Subtitle>ELIGIBILITY</Subtitle>

        <Para>
          a. You represent and warrant that you are competent and eligible to
          enter into legally binding agreements and of age and that you have the
          requisite authority to bind themselves to these Terms of Use following
          the Law. However, if you are minor using this Website and Application,
          you may do so with the consent of your legal guardian. All Acts of
          minor shall be deemed to be considered as the acts undertaken under
          the supervision of their legal guardian. b. You further represent that
          you will comply with these Terms of Use and all applicable local,
          state, national and international laws, rules and regulations. c. You
          shall not use the Website and Application if you are not competent to
          contract or are disqualified from doing so by any other applicable
          law, rule or regulation currently in force.
        </Para>

        <Subtitle>PAYMENT GATEWAY</Subtitle>

        <Para>
          For making all payments for availing consultancy, you shall be
          required to make payment for which you will be redirected to a third
          party payment gateway that we may have an agreement with. You shall be
          governed under their Terms and Conditions and other Policies for the
          purpose of all Payment related aspects.
        </Para>

        <Subtitle>CONTENT</Subtitle>
        <Para>
          All text, graphics, User interfaces, visual interfaces, photographs,
          trademarks, logos, brand names, descriptions, sounds, music and
          artwork (collectively, ‘Content’), is generated/provided or based on
          information provided by the users or third parties and We has no
          control and make no guarantees regarding the quality, the accuracy,
          integrity or genuineness of such content or such other information
          provided on the Website and Application. All the Content displayed on
          the Website and Application is subject to copyright and shall not be
          reused by You (or a third party) without the prior written consent
          from Us and the copyright owner. You are solely responsible for the
          integrity, authenticity, quality and genuineness of the content
          provided on the Website and Application and whilst feedback and
          comments by You can be made via the Website and Application, We bear
          no liability whatsoever for any feedback or comments made by the other
          Users or made in respect of any of the content on the Website and
          Application. Further, the Website and Application reserves its right
          to suspend the account of any User for an indefinite period to be
          decided at the discretion of the Website and Application or to
          terminate the account of any User who is found to have created or
          shared or submitted any content or part thereof that is found to be
          untrue/inaccurate/misleading or offensive/vulgar. You shall be solely
          responsible for making good any financial or legal losses incurred
          through the creation/sharing/submission of Content or part thereof
          that is deemed to be untrue/inaccurate/misleading. You have a
          personal, non-exclusive, non-transferable, revocable, limited
          privilege to access the content on the Website and Application. You
          shall not copy, adapt, and modify any content without written
          permission from Us. Please note that once the fee is paid, no refunds
          will be issued under any circumstances. The program fee is final and
          non-refundable.
        </Para>

        <Subtitle>INDEMNITY</Subtitle>
        <Para>
          You agree to indemnify, defend and hold harmless the Us, and our
          respective directors, officers, employees and agents (collectively,
          "Parties"), from and against any losses, liabilities, claims, damages,
          demands, costs and expenses (including legal fees and disbursements in
          connection therewith and interest chargeable thereon) asserted against
          or incurred by Us that arise out of, result from, or maybe payable by,
          any breach or nonperformance of any representation, warranty, covenant
          or agreement made or obligation to be performed according to these
          Terms of Use. Further, You agrees to hold the Us harmless against any
          claims made by any third party due to, or arising out of, or in
          connection with: a. Your use of the Website and Application, b. Your
          violation of these Terms of Use; c. Your violation of any rights of
          another; d. Your alleged improper conduct according to these Terms of
          use; e. Your conduct in connection with the Website and Application;
          You agree to fully cooperate in indemnifying Us at your expense. You
          also agree not to settle with any party without the consent from Us.
          In no event shall we be liable to compensate You or any third party
          for any special, incidental, indirect, consequential or punitive
          damages whatsoever, including those resulting from loss of use, data
          or profits, whether or not foreseeable, and whether or not You had
          been advised of the possibility of such damages, or based on any
          theory of liability, including breach of contract or warranty,
          negligence or other tortuous action, or any other claim arising out of
          or in connection with the Your use of or access to the Website and
          Application and/or the Services or materials contained therein.
        </Para>

        <Subtitle>LIMITATION OF LIABILITY</Subtitle>
        <Para>
          a. The Founders/ Promoters/ Partners/ Associated people of The Topper
          Academy are not responsible for any consequences arising out of the
          following events: i.If the Website and Application is
          inoperative/non-responsive due to any connectivity errors associated
          with the internet connection such as but not limited to slow
          connectivity, no connectivity, server failure; ii.If you have fed
          incorrect information or data or for any deletion of data; iii.If
          there is an undue delay or inability to communicate through email;
          iv.If there is any deficiency or defect in the Services managed by Us;
          v.If there is a failure in the functioning of any other service
          provided by Us. b. The Website and Application accepts no liability
          for any errors or omissions, on behalf of itself, or for any damage
          caused to You, Your belongings, or any third party, resulting from the
          use or misuse of the Website and Application or any service availed of
          by Us through the Website and Application. The service and any Content
          or material displayed on the service is provided without any
          guarantees, conditions or warranties as to its accuracy, suitability,
          completeness or reliability. We will not be liable to you for the
          unavailability or failure of the Website and Application. c. You are
          to comply with all laws applicable to you or your activities, and with
          all Policies, which are hereby incorporated into this Terms of Use by
          reference. d. The Website and Application expressly excludes any
          liability for any loss or damage that was not reasonably foreseeable
          by the Website and Application and which is incurred by you in
          connection with the Website and Application, including loss of
          profits; and any loss or damage incurred by you as a result of your
          breach of these Terms of Use. e. To the fullest extent permitted by
          law, We shall not be liable to You or any other party for any loss or
          damage, regardless of the form of action or basis of any claim. You
          acknowledge and agree that your sole and exclusive remedy for any
          dispute with us is to terminate your use of the Website and
          Application.
        </Para>

        <Subtitle>TERM</Subtitle>
        <Para>
          a. These Terms of Use shall continue to form a valid and binding
          contract between You and Us and shall continue to be in full force and
          effect until You continues to access and use the Website and
          Applications. b. You may terminate your use of the Website and
          Application at any time. c. We may terminate these Terms of Use and
          close your account at any time without notice and/or suspend or
          terminate Your access to the Website and Application at any time and
          for any reason, if any discrepancy or legal issue arises.
        </Para>

        <Subtitle>TERMINATION</Subtitle>

        <Para>
          We reserve the right, in its sole discretion, to unilaterally
          terminate Your access to the Website and Application, or any portion
          thereof, at any time, without notice or cause.
        </Para>

        <Subtitle>COMMUNICATION</Subtitle>
        <Para>
          By using this Website and Application and providing Your identity and
          contact information to Us through the Website and Application, You
          agree and consent to receive calls, e-mails or SMS from Us and/or any
          of its representatives at any time. You can report to
          “info@thetopperacademy.com” if you find any discrepancy with regard to
          Website and Application or content-related information and We will
          take necessary action after an investigation. The response with
          resolution (if any issues found) shall be dependent on the time is
          taken for investigation. You expressly agree that notwithstanding
          anything contained hereinabove, it may be contacted by Us relating to
          any services availed by You on the Website and Application or anything
          pursuant thereto and You agree to indemnify Us from any harassment
          claims. It is expressly agreed to by Us that any information shared by
          Us shall be governed by the Privacy Policy.
        </Para>

        <Subtitle>
          USER OBLIGATIONS AND FORMAL UNDERTAKINGS AS TO CONDUCT
        </Subtitle>
        <Para>
          You agree and acknowledges that you are a restricted user of this
          Website and Application and you: a. Agree to provide genuine
          credentials during the process of registration on the Website and
          Application. You shall not use a fictitious identity to register. We
          are not liable if You have provided incorrect information. b. Agree to
          ensure the Name, Email address, Address, Mobile number and any such
          other information provided during account registration is valid at all
          times and shall keep your information accurate and up-to-date. c. You
          agree that You are solely responsible for maintaining the
          confidentiality of your account password. You agree to notify us
          immediately of any unauthorized use of your account. We reserve the
          right to close your account at any time for any or no reason. d.
          Understand and acknowledge that the data submitted is manually entered
          into the database of the Website and Application. You also acknowledge
          the fact that data so entered into the database is for easy and ready
          reference for You, and to streamline the Services through the Website
          and Application. e. Authorize the Website and Application to use,
          store or otherwise process certain personal information and all
          published Content, responses, locations, User comments, reviews and
          ratings for personalization of Services, marketing and promotional
          purposes and for optimisation of User-related options and Services. f.
          Understand and agree that, to the fullest extent permissible by law,
          the Website and Application or any of their affiliates or their
          respective officers, directors, employees, agents, licensors,
          representatives, operational service providers, advertisers or
          suppliers shall not be liable for any loss or damage, of any kind,
          direct or indirect, in connection with or arising from the use of the
          Website and Application or this terms of use, including, but not
          limited to, compensatory, consequential, incidental, indirect, special
          or punitive damages. g. Are bound not to cut, copy, modify, recreate,
          reverse engineer, distribute, disseminate, post, publish or create
          derivative works from, transfer, or sell any information or obtained
          from the Website and Application. Any such use/limited use of the
          Website and Application will only be allowed with the prior express
          written permission. h. Agree not to access (or attempt to access) the
          Website and Application and/or the materials or Services by any means
          other than through the interface provided by the Website and
          Application. The use of deep-link, robot, spider or other automatic
          devices, program, algorithm or methodology, or any similar or
          equivalent manual process, to access, acquire, copy or monitor any
          portion of the Website and Application or its content, or in any way
          reproduce or circumvent the navigational structure or presentation of
          the Website and Application, materials or any content, or to obtain or
          attempt to obtain any materials, documents or information through any
          means not specifically made available through the Website and
          Application will lead to suspension or termination of your access to
          the Website and Application. We disclaim any liabilities arising
          concerning such offensive content on the Website and Application. i.
          Expressly agree and acknowledge that the Content generated by the
          Users and displayed on the Website and Application is not owned by Us
          and that We are in no way responsible for the content of the same. You
          may, however, report any offensive or objectionable content, which We
          may then remove from the Website and Application, at our sole
          discretion. j. Users have the option to switch to the next available
          batch or program before the commencement of the current batch.
          However, once the reversal program has started, switching to a
          different batch is not allowed. During the course of the program,
          switching to a different batch is not feasible. Participants who wish
          to join a future batch must withdraw from the current program and
          re-enroll in the desired batch, subject to availability and applicable
          fees. Once the program has commenced, refunds will not be provided on
          the grounds of being unable to follow the program protocols. The
          program is structured to support participants at various levels of
          engagement, and personalized assistance is available to help overcome
          challenges. Participants are encouraged to seek guidance and make
          necessary adjustments to stay on track. You further undertake not to:
          a. Engage in any activity that interferes with or disrupts access to
          the Website and Application or the Services provided therein (or the
          servers and networks which are connected to the Website and
          Application); b. Impersonate any person or entity, or falsely state or
          otherwise misrepresent his/her affiliation with a person or entity; c.
          Probe, scan or test the vulnerability of the Website and Application
          or any network connected to the Website and Application, nor breach
          the security or authentication measures on the Website and Application
          or any network connected to the Website and Application. The User may
          not reverse look-up, trace or seek to trace any information relating
          to any other User of, or visitor to, the Website and Application, or
          any other viewer of the Website and Application, including any User
          account maintained on the Website and Application not operated/managed
          by the User, or exploit the Website and Application or information
          made available or offered by or through the Website and Application,
          in any manner; d. Disrupt or interfere with the security of, or
          otherwise cause harm to, the Website and Application, systems
          resources, accounts, passwords, servers, or networks connected to or
          accessible through the Website and Application or any affiliated or
          linked and Website and Applications. e. Use the Website and
          Application or any material or content therein for any purpose that is
          unlawful or prohibited by these Terms of Use, or to solicit the
          performance of any illegal activity or other activity which infringes
          the rights of this Website and Application or any other third party
          (s); f. Violate any code of conduct or guideline which may apply for
          or to any particular service offered on the Website and Application;
          g. Violate any applicable laws, rules or regulations currently in
          force within or outside India; h. Violate any portion of these Terms
          of Use or the Privacy Policy, including but not limited to any
          applicable additional terms of the Website and Application contained
          herein or elsewhere, whether made by amendment, modification, or
          otherwise; i. Commit any act that causes Us to lose (in whole or in
          part) the Services of its Internet Establishment ("ISP") or in any
          manner disrupts the Services of any other supplier/service provider of
          the Website and Application; Further: j. You hereby expressly
          authorize Us to disclose any and all information relating to You in
          our possession to law enforcement or other government officials, as We
          may in our sole discretion, believe necessary or appropriate in
          connection with the investigation and/or resolution of possible
          crimes, especially those involve personal injury and
          theft/infringement of intellectual property. You further understand
          that the Website and Application might be directed to disclose any
          information (including the identity of persons providing information
          or materials on the Website and Application) as necessary to satisfy
          any judicial Order, law, regulation or valid governmental request. k.
          By indicating Your acceptance to use any services offered on the
          Website and Application, You are obligated to complete such
          transactions after making payment. You shall be prohibited from
          indicating their acceptance to avail services where the transactions
          have remained incomplete. l. You agree to use the services provided by
          Us, our affiliates, consultants and contracted companies, for lawful
          purposes only. m. You agree to provide authentic and true information.
          We reserve the right to confirm and validate the information and other
          details provided by You at any point in time. If upon confirmation
          such details are found to be false, not to be true (wholly or partly),
          We shall in our sole discretion reject the registration and debar You
          from using the Website and Application without prior intimation
          whatsoever. n. You agree not to post any material on the Website and
          Application that is defamatory, offensive, obscene, indecent, abusive,
          or needlessly distressful or advertising any goods or services. More
          specifically, You agree not to host, display, upload, update, publish,
          modify, transmit, or in any manner share any information that:
          i.belongs to another person and to which you have no right to; ii.is
          grossly harmful, harassing, blasphemous, defamatory, obscene,
          pornographic, pedophilic, libellous, invasive of another's privacy,
          hateful, or racially, ethnically objectionable, disparaging, relating
          or encouraging money laundering or gambling, or otherwise unlawful in
          any manner whatever; iii.is in any way harmful to minors; iv.infringes
          any patent, trademark, copyright or other proprietary rights;
          v.violates any law for the time being in force; vi.Publish, post,
          disseminate, any grossly harmful information, harassing, blasphemous,
          defamatory, obscene, pornographic, pedophilic, libellous, invasive of
          another's privacy, hateful, or racially, ethnically objectionable,
          disparaging, relating or encouraging money laundering or gambling, or
          otherwise unlawful in any manner whatever; or unlawfully threatening
          or unlawfully harassing including but not limited to "indecent
          representation of women" within the meaning of the Indecent
          Representation of Women (Prohibition) Act, 1986; vii.Threatens the
          unity, integrity, defence, security or sovereignty of India, friendly
          relations with foreign states, or public order or causes incitement to
          the commission of any cognizable offence or prevents investigation of
          any offence or is insulting any other nation.
        </Para>

        <Subtitle>SUSPENSION OF USER ACCESS AND ACTIVITY</Subtitle>

        <Para>
          Notwithstanding other legal remedies that may be available, we may in
          our sole discretion, limit the You access and/or activity by
          immediately removing your access credentials either temporarily or
          indefinitely, or suspend/terminate your association with the Website
          and Application, and/or refuse to the usage of the Website and
          Application, without being required to provide you with notice or
          cause: a. If you are in breach any of these Terms of Use or the
          Privacy Policy; b. If you have provided wrong, inaccurate, incomplete
          or incorrect information; c. If your actions may cause any harm,
          damage or loss to the other Users or Us, at our sole discretion.
        </Para>

        <Subtitle>INTELLECTUAL PROPERTY RIGHTS</Subtitle>

        <Para>
          Unless expressly agreed to in writing, nothing contained herein shall
          give You a right to use any of the Website and Application’s trade
          names, trademarks, service marks, logos, domain names, information,
          questions, answers, solutions, reports and other distinctive brand
          features, save according to the provisions of these Terms of Use. All
          logos, trademarks, brand names, service marks, domain names, including
          material, designs, and graphics created by and developed by the
          Website and Application and other distinctive brand features of the
          Website and Application are the property of the Website and
          Application or the respective copyright or trademark owner.
          Furthermore, concerning the Website and Application, we shall be the
          exclusive owner of all the designs, graphics and the like, related to
          the Website and Application. You shall not use any of the intellectual
          property displayed on the Website and Application in any manner that
          is likely to cause confusion among existing or prospective Users of
          the Website and Application, or that in any manner disparages or
          discredits the Website and Application, to be determined in the sole
          discretion. You are aware all intellectual property, including but not
          limited to copyrights, relating to said services resides with the
          owners, and that at no point does any such intellectual property stand
          transferred from the aforementioned creators. You are aware that we
          merely provide the Website and Application through which the You can
          communicate with other users and the Website and Application does not
          own any of the intellectual property relating to the independent
          content displayed on the Website and Application, apart from created
          graphics and specified content. You are further aware that any
          reproduction or infringement of the intellectual property of the
          aforementioned owners by You will result in legal action being
          initiated against You by the respective owners of the intellectual
          property so reproduced/infringed upon. It is agreed to by You that the
          contents of this Section shall survive even after the termination or
          expiry of these Terms of Use and/or Privacy Policy.
        </Para>

        <Subtitle>DISCLAIMER OF WARRANTIES AND LIABILITIES</Subtitle>
        <Para>
          a. You further agree and undertake that you are accessing the Website
          and Application at your sole risk and are that you are using the best
          and prudent judgment before availing any features on the Website and
          Application or accessing/using any information displayed thereon. b.
          You agree that any kind of information, resources, activities,
          recommendations obtained/availed from Website and Application, written
          or oral, will not create any warranty and we disclaim all liabilities
          resulting from these. c. We do not guarantee that the features and
          content contained in the Website and Application will be uninterrupted
          or error-free, or that the Website and Application or its server will
          be free of viruses or other harmful components, and You hereby
          expressly accepts any associated risks involved with your use of the
          Website and Application. d. It is further agreed to by You that the
          contents of this Section shall survive even after the termination or
          expiry of the Terms of Use and/or Privacy Policy. e. While we strive
          for our Expert Services to be beneficial, it is important to
          understand, agree, and acknowledge that they may not be suitable for
          everyone's needs or appropriate for every specific situation. Our
          services may not serve as a substitute for certain mental health
          requirements that necessitate in-person therapy services, such as
          active substance withdrawal or anorexia nervosa treatment.
        </Para>

        <Subtitle>FORCE MAJEURE</Subtitle>

        <Para>
          We will not be liable for damages for any delay or failure to perform
          our obligations hereunder if such delay or failure is due to cause
          beyond our control or without its fault or negligence, due to Force
          Majeure events including but not limited to acts of war, acts of God,
          earthquake, riot, fire, festive activities sabotage, labour shortage
          or dispute, internet interruption, technical failure, breakage of sea
          cable, hacking, piracy, cheating, illegal or unauthorized.
        </Para>

        <Subtitle>DISPUTE RESOLUTION AND JURISDICTION</Subtitle>

        <Para>
          It is expressly agreed to by You hereto that the formation,
          interpretation, and performance of these Terms of Use and any disputes
          arising therefrom will be resolved through Arbitration. It is further
          agreed to by You that the contents of this Section shall survive even
          after the termination or expiry of the Terms of Use and/or Privacy
          Policy. Arbitration: In the event that the Parties are unable to
          amicably resolve a dispute, the said dispute will be referred to
          arbitration by a sole arbitrator to be appointed by Us, and the award
          passed by such sole arbitrator will be valid and binding on all
          parties. All cost of the Arbitration shall be borne solely in
          accordance with the Arbitrators award. The arbitration shall be
          conducted in English, and the seat of Arbitration shall be the city of
          Bangalore, India. You expressly agree that the Terms of Use, Privacy
          Policy and any other agreements entered into between the Parties are
          governed by the laws, rules, and regulations of India.
        </Para>

        <Subtitle>MISCELLANEOUS PROVISIONS</Subtitle>

        <Para>
          a. Entire Agreement: These Terms of Use, read with the Privacy Policy,
          form the complete and final contract between the You and Us with
          respect to the subject matter hereof and supersedes all other
          communications, representations, and agreements (whether oral, written
          or otherwise) relating thereto. b. Waiver: The failure of either Party
          at any time to require performance of any provision of these Terms of
          Use shall in no manner affect such Party's right at a later time to
          enforce the same. No waiver by either party of any breach of these
          Terms of Use, whether by conduct or otherwise, in any one or more
          instances, shall be deemed to be or construed as a further or
          continuing waiver of any such breach, or a waiver of any other breach
          of these Terms of Use. c. Severability: If any provision/clause of
          these Terms of Use is held to be invalid, illegal or unenforceable by
          any court or authority of competent jurisdiction, the validity,
          legality, and enforceability of the remaining provisions/clauses of
          these Terms of Use shall in no way be affected or impaired thereby,
          and each such provision/clause of these Terms of Use shall be valid
          and enforceable to the fullest extent permitted by law. In such case,
          these Terms of Use shall be reformed to the minimum extent necessary
          to correct any invalidity, illegality or unenforceability, while
          preserving to the maximum extent the original rights, intentions and
          commercial expectations of the Parties hereto, as expressed herein d.
          Contact Us: If you have any questions about these Terms of Use or the
          Privacy Policy, the practices of the Website and Application, or your
          experience, you can contact us at “info@thetopperacademy.com".
        </Para>
      </TermContainer>
    </Container>
  );
};

export default TermsConditionSettings;
